name: Weekly Docker Build

on:
  schedule:
    - cron: '0 11 * * 6'  # jeden Samstag um 11:00 UTC

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest .

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository }}:latest

